// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPMGrDeM5o51zpi-4J-0rVMAb23MOJ2Wc',
    appId: '1:1042114486220:web:d5d58f83f38934d683c769',
    messagingSenderId: '1042114486220',
    projectId: 'first-flutter-b3ad6',
    authDomain: 'first-flutter-b3ad6.firebaseapp.com',
    storageBucket: 'first-flutter-b3ad6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5nah-FVLxwlO6m6qNMkauB6Q-3sWix0Q',
    appId: '1:1042114486220:android:92d0d3bae5711c1b83c769',
    messagingSenderId: '1042114486220',
    projectId: 'first-flutter-b3ad6',
    storageBucket: 'first-flutter-b3ad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMWogzrrw2-CnrOjXXvEVX6HOotbUTJ4o',
    appId: '1:1042114486220:ios:31f85eea42a5a79983c769',
    messagingSenderId: '1042114486220',
    projectId: 'first-flutter-b3ad6',
    storageBucket: 'first-flutter-b3ad6.appspot.com',
    iosClientId: '1042114486220-hp3b5cch7mq19eh8d4s1bjea8ecsu720.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstFlutter',
  );
}
